import type { TemplateModelConfig } from '../types';

export const WAN_VIDEO_MODELS: TemplateModelConfig[] = [
  {
    id: 'wan-2.7-text-to-video',
    label: 'Wan 2.7',
    mediaType: 'video',
    request: {
      endpoint: 'video',
      modelName: 'wan-2.7-text-to-video',
    },
    inputs: {
      prompt: { supported: true, required: true },
      startFrame: { supported: false, required: false },
      endFrame: { supported: false, required: false },
      audio: { supported: true, required: false },
    },
    params: {
      ratio: ['16:9', '9:16', '1:1', '4:3', '3:4'],
      resolution: ['720p', '1080p'],
      durationRange: { min: 2, max: 15 },
      seed: true,
      negativePrompt: true,
    },
  },
  {
    id: 'wan-2.7-image-to-video',
    label: 'Wan 2.7',
    mediaType: 'video',
    request: {
      endpoint: 'video',
      modelName: 'wan-2.7-image-to-video',
    },
    inputs: {
      prompt: { supported: true, required: true },
      startFrame: { supported: true, required: true },
      endFrame: { supported: true, required: false },
      video: { supported: true, required: false },
      audio: { supported: true, required: false },
    },
    params: {
      resolution: ['720p', '1080p'],
      durationRange: { min: 2, max: 15 },
      seed: true,
      negativePrompt: true,
    },
  },
  {
    id: 'wan-3.0-text-to-video',
    label: 'Wan 3.0 Text to Video',
    mediaType: 'video',
    provider: 'wan',
    generationType: 'text-to-video',
    request: {
      endpoint: 'video',
      modelName: 'wan-3.0-text-to-video',
    },
    inputs: {
      prompt: { supported: true, required: true },
      startFrame: { supported: false, required: false },
      endFrame: { supported: false, required: false },
    },
    params: {
      ratio: ['16:9', '9:16', '1:1', '4:3', '3:4'],
      resolution: ['480p', '720p', '1080p'],
      durationRange: { min: 2, max: 30 },
      sound: true,
      defaultSound: true,
      seed: { min: 0, max: 2147483647 },
    },
  },
  {
    id: 'wan-3.0-image-to-video',
    label: 'Wan 3.0 Image to Video',
    mediaType: 'video',
    provider: 'wan',
    generationType: 'image-to-video',
    request: {
      endpoint: 'video',
      modelName: 'wan-3.0-image-to-video',
    },
    inputs: {
      prompt: { supported: true, required: true },
      startFrame: { supported: true, required: true },
      endFrame: { supported: true, required: true },
    },
    params: {
      ratio: ['16:9', '9:16', '1:1', '4:3', '3:4'],
      resolution: ['480p', '720p', '1080p'],
      durationRange: { min: 2, max: 30 },
      sound: true,
      defaultSound: true,
      seed: { min: 0, max: 2147483647 },
    },
  },
  {
    id: 'wan-3.0-reference-to-video',
    label: 'Wan 3.0 Reference to Video',
    mediaType: 'video',
    provider: 'wan',
    generationType: 'reference-to-video',
    request: {
      endpoint: 'video',
      modelName: 'wan-3.0-reference-to-video',
    },
    inputs: {
      prompt: { supported: true, required: true },
      image: {
        supported: true,
        required: false,
        multiple: true,
        min: 0,
        max: 10,
        minSidePx: 240,
        maxSidePx: 8000,
        acceptedFormats: ['jpg', 'jpeg', 'png', 'bmp', 'webp'],
        allowAlphaChannel: false,
      },
      video: {
        supported: true,
        required: false,
        multiple: true,
        min: 0,
        max: 5,
        minDurationSeconds: 1,
        maxDurationSeconds: 15,
        maxTotalDurationSeconds: 15,
        minSidePx: 240,
        maxSidePx: 4096,
        acceptedFormats: ['mp4', 'mov'],
      },
      audio: {
        supported: true,
        required: false,
        multiple: true,
        min: 0,
        max: 5,
        minDurationSeconds: 1,
        maxDurationSeconds: 15,
        maxTotalDurationSeconds: 15,
        acceptedFormats: ['wav', 'mp3'],
      },
      file: {
        supported: true,
        required: false,
        max: 1,
        acceptedFormats: ['docx', 'doc', 'xlsx', 'xls', 'pptx', 'ppt', 'pdf', 'txt', 'key', 'pages', 'numbers', 'md'],
        maxPages: 50,
      },
      link: { supported: true, required: false, max: 1 },
      startFrame: { supported: false, required: false },
      endFrame: { supported: false, required: false },
    },
    params: {
      ratio: ['16:9', '9:16', '1:1', '4:3', '3:4'],
      resolution: ['480p', '720p', '1080p'],
      durationRange: { min: 2, max: 30 },
      sound: true,
      defaultSound: true,
      seed: { min: 0, max: 2147483647 },
      independentReferenceLimits: true,
    },
  },
];
